### PR TITLE
Upgraded to NewRelic 4.1.0

### PR DESCRIPTION
**Pull request by donbeave**
Also updated to Grails 3.3.5 and added Gradle Artifactory plugin, to have an ability to upload plugin in internal repo .

### CODE REVIEW

**Comment by musketyr** [comment]
thanks, @donbeave. I will need a bit of time to dig properly into all the changes but the PR should be processed until the end of the week

**Comment by donbeave** [comment]
Thank you!

Looking forward

**Comment by musketyr** [comment]
looks good, thank you again for your contribution!

**Comment by musketyr** [comment]
hi @donbeave - after merging this request there is no longer any pom file nor source file published to Maven repository causing the transitive dependencies to be lost. do you have any idea what can be the reason?

**Comment by musketyr** [comment]
I'm sorry I had to revert the plugin as it stopped publishing the POM file to BinTray. if you can submit your changes *without* upgrading Gradle and Grails I'm happy to merge the changes again.

**Comment by donbeave** [comment]
Ok, @musketyr, no problem, I'll make another PR with fixes.

**Pull request merged**
